apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-craft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memo-craft
  template:
    metadata:
      labels:
        app: memo-craft
    spec:
      containers:
        - name: memo-craft
          image: wutiandengdai/memo-craft
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/memo_craft"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/memo_craft_text"
---
apiVersion: v1
kind: Service
metadata:
  name: memo-craft
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: memo-craft
