apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  postgres-username: bWVtb19jcmFmdA==
  postgres-password: eW91cl9wb3N0Z3Jlc19wYXNzd29yZA==
  mongo-initdb-database: bWVtb19jcmFmdF90ZXh0
